import {
  ChevronDown,
  LogOut,
  LayoutDashboard,
  Search,
  FileText,
  Car,
  Users,
  Settings,
  Shield,
  ClipboardList,
  Package,
  UserCircle,
  BarChart3,
  Wrench,
  X,
} from "lucide-react";

export const iconMap = {
  chevronDown: ChevronDown,
  logout: LogOut,
  dashboard: LayoutDashboard,
  search: Search,
  fileText: FileText,
  car: Car,
  users: Users,
  settings: Settings,
  shield: Shield,
  clipboardList: ClipboardList,
  package: Package,
  userCircle: UserCircle,
  barChart: BarChart3,
  wrench: Wrench,
  close: X,
} as const;
