/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVehicle_exchangeRouteImport } from './routes/_auth.vehicle_exchange'
import { Route as AuthSettingsRouteImport } from './routes/_auth.settings'
import { Route as AuthReturnRouteImport } from './routes/_auth.return'
import { Route as AuthReservation_lookupRouteImport } from './routes/_auth.reservation_lookup'
import { Route as AuthReportsRouteImport } from './routes/_auth.reports'
import { Route as AuthRentRouteImport } from './routes/_auth.rent'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthCarcontrolRouteImport } from './routes/_auth.carcontrol'
import { Route as AuthAaoRouteImport } from './routes/_auth.aao'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVehicle_exchangeRoute = AuthVehicle_exchangeRouteImport.update({
  id: '/vehicle_exchange',
  path: '/vehicle_exchange',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReturnRoute = AuthReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReservation_lookupRoute = AuthReservation_lookupRouteImport.update({
  id: '/reservation_lookup',
  path: '/reservation_lookup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsRoute = AuthReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRentRoute = AuthRentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCarcontrolRoute = AuthCarcontrolRouteImport.update({
  id: '/carcontrol',
  path: '/carcontrol',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAaoRoute = AuthAaoRouteImport.update({
  id: '/aao',
  path: '/aao',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/aao': typeof AuthAaoRoute
  '/carcontrol': typeof AuthCarcontrolRoute
  '/dashboard': typeof AuthDashboardRoute
  '/rent': typeof AuthRentRoute
  '/reports': typeof AuthReportsRoute
  '/reservation_lookup': typeof AuthReservation_lookupRoute
  '/return': typeof AuthReturnRoute
  '/settings': typeof AuthSettingsRoute
  '/vehicle_exchange': typeof AuthVehicle_exchangeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/aao': typeof AuthAaoRoute
  '/carcontrol': typeof AuthCarcontrolRoute
  '/dashboard': typeof AuthDashboardRoute
  '/rent': typeof AuthRentRoute
  '/reports': typeof AuthReportsRoute
  '/reservation_lookup': typeof AuthReservation_lookupRoute
  '/return': typeof AuthReturnRoute
  '/settings': typeof AuthSettingsRoute
  '/vehicle_exchange': typeof AuthVehicle_exchangeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_auth/aao': typeof AuthAaoRoute
  '/_auth/carcontrol': typeof AuthCarcontrolRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/rent': typeof AuthRentRoute
  '/_auth/reports': typeof AuthReportsRoute
  '/_auth/reservation_lookup': typeof AuthReservation_lookupRoute
  '/_auth/return': typeof AuthReturnRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/vehicle_exchange': typeof AuthVehicle_exchangeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/aao'
    | '/carcontrol'
    | '/dashboard'
    | '/rent'
    | '/reports'
    | '/reservation_lookup'
    | '/return'
    | '/settings'
    | '/vehicle_exchange'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/aao'
    | '/carcontrol'
    | '/dashboard'
    | '/rent'
    | '/reports'
    | '/reservation_lookup'
    | '/return'
    | '/settings'
    | '/vehicle_exchange'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/unauthorized'
    | '/_auth/aao'
    | '/_auth/carcontrol'
    | '/_auth/dashboard'
    | '/_auth/rent'
    | '/_auth/reports'
    | '/_auth/reservation_lookup'
    | '/_auth/return'
    | '/_auth/settings'
    | '/_auth/vehicle_exchange'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/vehicle_exchange': {
      id: '/_auth/vehicle_exchange'
      path: '/vehicle_exchange'
      fullPath: '/vehicle_exchange'
      preLoaderRoute: typeof AuthVehicle_exchangeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/return': {
      id: '/_auth/return'
      path: '/return'
      fullPath: '/return'
      preLoaderRoute: typeof AuthReturnRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reservation_lookup': {
      id: '/_auth/reservation_lookup'
      path: '/reservation_lookup'
      fullPath: '/reservation_lookup'
      preLoaderRoute: typeof AuthReservation_lookupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports': {
      id: '/_auth/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthReportsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/rent': {
      id: '/_auth/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof AuthRentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/carcontrol': {
      id: '/_auth/carcontrol'
      path: '/carcontrol'
      fullPath: '/carcontrol'
      preLoaderRoute: typeof AuthCarcontrolRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/aao': {
      id: '/_auth/aao'
      path: '/aao'
      fullPath: '/aao'
      preLoaderRoute: typeof AuthAaoRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAaoRoute: typeof AuthAaoRoute
  AuthCarcontrolRoute: typeof AuthCarcontrolRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthRentRoute: typeof AuthRentRoute
  AuthReportsRoute: typeof AuthReportsRoute
  AuthReservation_lookupRoute: typeof AuthReservation_lookupRoute
  AuthReturnRoute: typeof AuthReturnRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthVehicle_exchangeRoute: typeof AuthVehicle_exchangeRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAaoRoute: AuthAaoRoute,
  AuthCarcontrolRoute: AuthCarcontrolRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthRentRoute: AuthRentRoute,
  AuthReportsRoute: AuthReportsRoute,
  AuthReservation_lookupRoute: AuthReservation_lookupRoute,
  AuthReturnRoute: AuthReturnRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthVehicle_exchangeRoute: AuthVehicle_exchangeRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
