import { TableType } from "../types/type";

export const rentedVehiclesMock:TableType[] = [
  {
    id: "1",
    customerName: "John Doe",
    serviceLevel: "Gold",
    cvi: "CVI123",
    estArrival: "10:00",
    flightInfoStatus: "On Time",
    numberOfDays: 3,
    resClass: "Economy",
    resStatus: "Confirmed",
    dashStatus: "Active",
    rentDate: "2025-01-01",
    returnDate: "2025-01-04",
    arrivalLocation: "DEL",
    email: "john@test.com",
    phone: "9999999999",
  },
  {
    id: "2",
    customerName: "Jane Smith",
    serviceLevel: "Silver",
    cvi: "CVI456",
    estArrival: "12:00",
    flightInfoStatus: "Delayed",
    numberOfDays: 2,
    resClass: "Business",
    resStatus: "Cancelled",
    dashStatus: "Inactive",
    rentDate: "2025-01-02",
    returnDate: "2025-01-04",
    arrivalLocation: "BLR",
    email: "jane@test.com",
    phone: "8888888888",
  },
  {
    id: "3",
    customerName: "Robert Wilson",
    serviceLevel: "Platinum",
    cvi: "CVI789",
    estArrival: "14:00",
    flightInfoStatus: "On Time",
    numberOfDays: 5,
    resClass: "Sedan",
    resStatus: "Completed",
    dashStatus: "Closed",
    rentDate: "2024-12-25",
    returnDate: "2024-12-30",
    arrivalLocation: "BOM",
    email: "robert@test.com",
    phone: "7777777777",
  },
  {
    id: "4",
    customerName: "Sarah Davis",
    serviceLevel: "Gold",
    cvi: "CVI012",
    estArrival: "09:30",
    flightInfoStatus: "Cancelled",
    numberOfDays: 7,
    resClass: "SUV",
    resStatus: "Confirmed",
    dashStatus: "Active",
    rentDate: "2025-01-05",
    returnDate: "2025-01-12",
    arrivalLocation: "HYD",
    email: "sarah@test.com",
    phone: "6666666666",
  },
  {
    id: "5",
    customerName: "Michael Johnson",
    serviceLevel: "Silver",
    cvi: "CVI345",
    estArrival: "11:00",
    flightInfoStatus: "Delayed",
    numberOfDays: 4,
    resClass: "Hatchback",
    resStatus: "Completed",
    dashStatus: "Closed",
    rentDate: "2024-12-28",
    returnDate: "2025-01-01",
    arrivalLocation: "DEL",
    email: "michael@test.com",
    phone: "5555555555",
  },
];