/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthScanPaymentIntegrationRouteImport } from './routes/_auth.scan-payment-integration'
import { Route as AuthReturnsRouteImport } from './routes/_auth.returns'
import { Route as AuthReservationLookupRouteImport } from './routes/_auth.reservation-lookup'
import { Route as AuthRentalAgreementGenerationRouteImport } from './routes/_auth.rental-agreement-generation'
import { Route as AuthGateVerificationRouteImport } from './routes/_auth.gate-verification'
import { Route as AuthDriversLicenseValidationRouteImport } from './routes/_auth.drivers-license-validation'
import { Route as AuthCarAvailabilityAssignmentRouteImport } from './routes/_auth.car-availability-assignment'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthScanPaymentIntegrationRoute =
  AuthScanPaymentIntegrationRouteImport.update({
    id: '/scan-payment-integration',
    path: '/scan-payment-integration',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthReturnsRoute = AuthReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReservationLookupRoute = AuthReservationLookupRouteImport.update({
  id: '/reservation-lookup',
  path: '/reservation-lookup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRentalAgreementGenerationRoute =
  AuthRentalAgreementGenerationRouteImport.update({
    id: '/rental-agreement-generation',
    path: '/rental-agreement-generation',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthGateVerificationRoute = AuthGateVerificationRouteImport.update({
  id: '/gate-verification',
  path: '/gate-verification',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDriversLicenseValidationRoute =
  AuthDriversLicenseValidationRouteImport.update({
    id: '/drivers-license-validation',
    path: '/drivers-license-validation',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthCarAvailabilityAssignmentRoute =
  AuthCarAvailabilityAssignmentRouteImport.update({
    id: '/car-availability-assignment',
    path: '/car-availability-assignment',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/car-availability-assignment': typeof AuthCarAvailabilityAssignmentRoute
  '/drivers-license-validation': typeof AuthDriversLicenseValidationRoute
  '/gate-verification': typeof AuthGateVerificationRoute
  '/rental-agreement-generation': typeof AuthRentalAgreementGenerationRoute
  '/reservation-lookup': typeof AuthReservationLookupRoute
  '/returns': typeof AuthReturnsRoute
  '/scan-payment-integration': typeof AuthScanPaymentIntegrationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/car-availability-assignment': typeof AuthCarAvailabilityAssignmentRoute
  '/drivers-license-validation': typeof AuthDriversLicenseValidationRoute
  '/gate-verification': typeof AuthGateVerificationRoute
  '/rental-agreement-generation': typeof AuthRentalAgreementGenerationRoute
  '/reservation-lookup': typeof AuthReservationLookupRoute
  '/returns': typeof AuthReturnsRoute
  '/scan-payment-integration': typeof AuthScanPaymentIntegrationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/car-availability-assignment': typeof AuthCarAvailabilityAssignmentRoute
  '/_auth/drivers-license-validation': typeof AuthDriversLicenseValidationRoute
  '/_auth/gate-verification': typeof AuthGateVerificationRoute
  '/_auth/rental-agreement-generation': typeof AuthRentalAgreementGenerationRoute
  '/_auth/reservation-lookup': typeof AuthReservationLookupRoute
  '/_auth/returns': typeof AuthReturnsRoute
  '/_auth/scan-payment-integration': typeof AuthScanPaymentIntegrationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/car-availability-assignment'
    | '/drivers-license-validation'
    | '/gate-verification'
    | '/rental-agreement-generation'
    | '/reservation-lookup'
    | '/returns'
    | '/scan-payment-integration'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/car-availability-assignment'
    | '/drivers-license-validation'
    | '/gate-verification'
    | '/rental-agreement-generation'
    | '/reservation-lookup'
    | '/returns'
    | '/scan-payment-integration'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/car-availability-assignment'
    | '/_auth/drivers-license-validation'
    | '/_auth/gate-verification'
    | '/_auth/rental-agreement-generation'
    | '/_auth/reservation-lookup'
    | '/_auth/returns'
    | '/_auth/scan-payment-integration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/scan-payment-integration': {
      id: '/_auth/scan-payment-integration'
      path: '/scan-payment-integration'
      fullPath: '/scan-payment-integration'
      preLoaderRoute: typeof AuthScanPaymentIntegrationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/returns': {
      id: '/_auth/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof AuthReturnsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reservation-lookup': {
      id: '/_auth/reservation-lookup'
      path: '/reservation-lookup'
      fullPath: '/reservation-lookup'
      preLoaderRoute: typeof AuthReservationLookupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/rental-agreement-generation': {
      id: '/_auth/rental-agreement-generation'
      path: '/rental-agreement-generation'
      fullPath: '/rental-agreement-generation'
      preLoaderRoute: typeof AuthRentalAgreementGenerationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gate-verification': {
      id: '/_auth/gate-verification'
      path: '/gate-verification'
      fullPath: '/gate-verification'
      preLoaderRoute: typeof AuthGateVerificationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/drivers-license-validation': {
      id: '/_auth/drivers-license-validation'
      path: '/drivers-license-validation'
      fullPath: '/drivers-license-validation'
      preLoaderRoute: typeof AuthDriversLicenseValidationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/car-availability-assignment': {
      id: '/_auth/car-availability-assignment'
      path: '/car-availability-assignment'
      fullPath: '/car-availability-assignment'
      preLoaderRoute: typeof AuthCarAvailabilityAssignmentRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCarAvailabilityAssignmentRoute: typeof AuthCarAvailabilityAssignmentRoute
  AuthDriversLicenseValidationRoute: typeof AuthDriversLicenseValidationRoute
  AuthGateVerificationRoute: typeof AuthGateVerificationRoute
  AuthRentalAgreementGenerationRoute: typeof AuthRentalAgreementGenerationRoute
  AuthReservationLookupRoute: typeof AuthReservationLookupRoute
  AuthReturnsRoute: typeof AuthReturnsRoute
  AuthScanPaymentIntegrationRoute: typeof AuthScanPaymentIntegrationRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCarAvailabilityAssignmentRoute: AuthCarAvailabilityAssignmentRoute,
  AuthDriversLicenseValidationRoute: AuthDriversLicenseValidationRoute,
  AuthGateVerificationRoute: AuthGateVerificationRoute,
  AuthRentalAgreementGenerationRoute: AuthRentalAgreementGenerationRoute,
  AuthReservationLookupRoute: AuthReservationLookupRoute,
  AuthReturnsRoute: AuthReturnsRoute,
  AuthScanPaymentIntegrationRoute: AuthScanPaymentIntegrationRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
